name: pokedex
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^11.1.2
  device_preview: ^1.1.0
  flutter_riverpod: ^2.3.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.1.0
  path_provider: ^2.1.1
  fraction: ^5.0.2
  video_editor: ^3.0.0
  ffmpeg_kit_flutter: ^6.0.3
  sqflite: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.3
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/json/
    - assets/fonts/OFL.txt
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Bold.otf
        - asset: assets/fonts/NotoSansJP-Regular.otf
